services:
  nginx:
    image: 'nginx:1.27.0-bookworm'
    volumes:
      - ./nginx/production.conf:/etc/nginx/nginx.conf
      - ./certs:/certs
      - ./certs:/etc/nginx/certs
    command: ['nginx', '-g', 'daemon off;']
    restart: always
    ports:
      - 443:443
    networks:
      - public
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'service', 'nginx', 'status']
      interval: 30s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile.production
      target: production
    env_file:
      - .env.production
    command: ['yarn', 'start']
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - public
      - internal
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:3000/api/health']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

networks:
  public: {}
  internal: {}
