services:
  nginx:
    image: 'nginx:1.27.0-bookworm'
    volumes:
      - ./nginx/production.conf:/etc/nginx/nginx.conf
      # - ./certs:/certs
      - ./certs:/etc/nginx/certs:ro # Origin CA cert
      - /etc/letsencrypt:/etc/letsencrypt:ro
      # - /etc/letsencrypt:/etc/letsencrypt:ro
      # - /etc/nginx/nginx.conf:/etc/nginx:ro
      # Optional dhparams mount if needed at a specific path
      # - /etc/letsencrypt/ssl-dhparams.pem:/etc/ssl/certs/dhparam.pem:ro
    command: ['nginx', '-g', 'daemon off;']
    restart: always
    ports:
      - 443:443
    networks:
      - public
    depends_on:
      app:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'service', 'nginx', 'status']
      interval: 30s
      timeout: 5s
      retries: 5

  app:
    labels:
      - 'deployment.version=${DEPLOYMENT_VERSION}'
    build:
      context: .
      dockerfile: Dockerfile.production
      target: production
      secrets:
        - cacert
    env_file:
      - .env.production
    command: ['yarn', 'start']
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - public
      - internal
    healthcheck:
      test: ['CMD', 'curl', '--fail', 'http://localhost:3000/api/health']
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 15s

secrets:
  cacert:
    file: /root/decentralizard/certs/prod-ca-2021.crt

networks:
  public: {}
  internal: {}
