{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secretName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.clusterSecretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.secretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecrets.keys }}
    - secretKey: {{ . }}
      remoteRef:
        key: {{ $.Values.externalSecrets.ssmPrefix }}/{{ . }}
    {{- end }}
{{- end }}
